#!/bin/bash
############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

# variables
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exclude=";$dir/.git;$dir/symlink;$dir/README.md;"
olddir=~/.dotfiles_old

# run within context of the symlink script directory
current=$(pwd)
cd $dir

# create dotfiles_old in homedir
mkdir -p $olddir

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file_path in $dir/*
do
  if [[ ! "$exclude" =~ ";$file_path;" ]]
  then
    _source=$(basename $file_path)
    _target_path=$(dirname ~/$_source)/.$_source
    _backup_dir=$(dirname $olddir)/$(basename $olddir)/
    _backup_path=$_backup_dir/.$_source

    # backup
    if [ -f $_target_path ] && [ ! -f $_backup_path ]
    then
      echo "backing up $_target_path to $_backup_dir"
      cp -n $_target_path $_backup_dir
    fi

    # create link
    rm $_target_path
    ln -s $file_path $_target_path
    echo "created symlink to $_target_path"
  fi
done

# return to original working directory
cd $current

