#!/bin/bash
############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

# variables
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exclude=";$dir/.git;$dir/symlink;$dir/README.md;"
olddir=~/.dotfiles_old

# run within context of the symlink script directory
current=$(pwd)
cd $dir

# create dotfiles_old in homedir
mkdir -p $olddir

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
shopt -s dotglob
for file_path in $dir/*
do
  if [[ ! "$exclude" =~ ";$file_path;" ]]
  then
    file=$(basename $file_path)

    # backup
    if [ -f ~/$file ] && [ ! -f $olddir/$file ]
    then
      echo "backing up $(dirname ~/$file)/$file to $(dirname $olddir)/$(basename $olddir)/"
      cp -n $(dirname ~/$file)/$file $(dirname $olddir)/$(basename $olddir)/
    fi

    # create link
    rm $(dirname ~/$file)/$file
    ln -s $file_path ~/$file
    echo "created symlink to ~/$file"
  fi
done

# return to original working directory
cd $current

